CREATE USER jogo WITH PASSWORD 'senhasupersegura';

GRANT CONNECT ON DATABASE one_piece TO jogo;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO jogo;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO jogo;

GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO jogo;

GRANT ALL PRIVILEGES ON DATABASE one_piece TO jogo;
