version: '3.1'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: one_piece
    volumes:
      - ./Modulo_3/SQL/ddl.sql:/docker-entrypoint-initdb.d/0ddl.sql
      - ./Modulo_3/trigger_stored_procedure.sql:/docker-entrypoint-initdb.d/1trigger_stored_procedure.sql
      - ./Modulo_3/SQL/dml.sql:/docker-entrypoint-initdb.d/2dml.sql
      - ./Modulo_3/SQL/create_user.sql:/docker-entrypoint-initdb.d/3create_user.sql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@email.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    depends_on:
      - db
    ports:
      - 8080:80
