version: '3.1'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: one_piece
    volumes:
      - ./game/setup/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql

  adminer:
    image: adminer
    ports:
      - 8080:8080
